export enum SubmissionStatus {
    QUEUED = "QUEUED",
    RUNNING = "RUNNING",
    ACCEPTED = "ACCEPTED",
    WRONG_ANSWER = "WRONG_ANSWER",
    SYNTAX_ERROR = "SYNTAX_ERROR",
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED",
    RUNTIME_ERROR = "RUNTIME_ERROR",
    OPTIMIZATION_REQUIRED = "OPTIMIZATION_REQUIRED"
}